import { ATLAS_LENSES } from "@/lib/atlas-lab/types";
import type {
  AtlasEdge,
  AtlasLabUrlState,
  AtlasLens,
  AtlasNode,
  AtlasSnapshot,
  AtlasStage,
} from "@/lib/atlas-lab/types";

const stages: AtlasStage[] = [
  {
    id: "early-universe",
    title: "Early universe / Big Bang",
    order: 1,
    timeLabel: "About 13.8 billion years ago",
    summary: "The hot, dense early state from which this represented developmental history begins.",
    accent: "#8178f2",
    primaryNodeId: "early-universe",
  },
  {
    id: "fundamental-forces-and-particles",
    title: "Forces and particles",
    order: 2,
    timeLabel: "The first fractions of a second onward",
    summary: "Interactions and particle populations set the working materials for later structure.",
    accent: "#718fe8",
    primaryNodeId: "fundamental-forces-and-particles",
  },
  {
    id: "atoms",
    title: "Atoms",
    order: 3,
    timeLabel: "Neutral atoms formed about 380,000 years after the Big Bang",
    summary: "Nuclei and electrons combined into stable neutral matter as the universe cooled.",
    accent: "#93b8ef",
    primaryNodeId: "atoms",
  },
  {
    id: "stars-and-heavy-elements",
    title: "Stars and heavy elements",
    order: 4,
    timeLabel: "The first stars formed roughly 100–200 million years later",
    summary: "Gravity built stellar furnaces that transformed light nuclei and enriched later systems.",
    accent: "#f0c678",
    primaryNodeId: "stars-and-heavy-elements",
  },
  {
    id: "planetary-systems",
    title: "Planetary systems",
    order: 5,
    timeLabel: "Our Solar System formed about 4.6 billion years ago",
    summary: "Enriched disks around stars organized into worlds, moons, and smaller bodies.",
    accent: "#d6a56e",
    primaryNodeId: "planetary-systems",
  },
  {
    id: "earth",
    title: "Earth",
    order: 6,
    timeLabel: "Earth formed about 4.54 billion years ago",
    summary: "A rocky world differentiated, cooled, cycled material, and retained surface water.",
    accent: "#b88e68",
    primaryNodeId: "earth",
  },
  {
    id: "life",
    title: "Life",
    order: 7,
    timeLabel: "Life existed by at least about 3.5 billion years ago",
    summary: "Matter became organized into bounded, self-maintaining, heritable systems.",
    accent: "#62bf91",
    primaryNodeId: "life",
  },
  {
    id: "multicellular-life",
    title: "Multicellular life",
    order: 8,
    timeLabel: "Complex multicellular forms diversified strongly around 600 million years ago",
    summary: "Cells cooperated, specialized, and built bodies with differentiated tissues.",
    accent: "#53b99d",
    primaryNodeId: "multicellular-life",
  },
  {
    id: "nervous-systems",
    title: "Nervous systems",
    order: 9,
    timeLabel: "Early animal nervous systems appeared more than 500 million years ago",
    summary: "Excitable cells coordinated sensing, action, memory, and behavior across bodies.",
    accent: "#45b4ad",
    primaryNodeId: "nervous-systems",
  },
  {
    id: "humans",
    title: "Humans",
    order: 10,
    timeLabel: "Homo sapiens appeared about 300,000 years ago",
    summary: "A social primate lineage developed unusually powerful cumulative learning and symbolic coordination.",
    accent: "#dc9d72",
    primaryNodeId: "humans",
  },
  {
    id: "culture",
    title: "Culture",
    order: 11,
    timeLabel: "Cumulative symbolic culture deepened across tens of thousands of years",
    summary: "Learned practices and meanings began persisting beyond individual lives.",
    accent: "#e29a70",
    primaryNodeId: "culture",
  },
  {
    id: "civilization",
    title: "Civilization",
    order: 12,
    timeLabel: "Large settlements, cities, and states developed over roughly the last 12,000 years",
    summary: "Dense populations coordinated through institutions, records, infrastructure, and specialized roles.",
    accent: "#e5ae69",
    primaryNodeId: "civilization",
  },
  {
    id: "science-technology-and-institutions",
    title: "Science, technology, and institutions",
    order: 13,
    timeLabel: "Organized knowledge and technical power accelerated over the last several centuries",
    summary: "Repeatable inquiry, engineered systems, and durable organizations amplified collective capability.",
    accent: "#e9c36e",
    primaryNodeId: "science-technology-and-institutions",
  },
  {
    id: "present-day",
    title: "Present day",
    order: 14,
    timeLabel: "Now — a shared planetary moment",
    summary: "Human, ecological, industrial, and information systems now interact at planetary scale.",
    accent: "#efd58a",
    primaryNodeId: "present-day",
  },
];

const nodes: AtlasNode[] = [
  {
    id: "early-universe",
    title: "The hot early universe",
    aliases: ["Big Bang", "hot Big Bang", "early cosmos"],
    kind: "stage",
    scale: "cosmic",
    stageId: "early-universe",
    displayOrder: 0,
    time: { label: "About 13.8 billion years ago", startYearsAgo: 13_800_000_000, precision: "approximate" },
    summary: "The observable hot, dense early state is the root of this represented history. This prototype does not claim that the known laws of physics themselves emerged from the Big Bang.",
    tags: ["cosmology", "origin history", "root", "compressed time"],
    formation: {
      prerequisites: [],
      transition: "Expansion and cooling changed which stable structures and interactions could leave lasting organization.",
      newlyPossible: ["long-lived particle populations", "light-element nuclei", "eventual neutral atoms"],
    },
    structure: {
      parts: ["radiation", "matter", "an expanding spacetime"],
      systems: ["thermal history", "density variation", "cosmic expansion"],
    },
    discovery: [
      {
        id: "expanding-universe-models",
        label: "Expanding-universe models",
        dateLabel: "1920s",
        people: ["Georges Lemaître", "Edwin Hubble"],
        summary: "Theory and astronomical observations established an expanding cosmic history.",
      },
      {
        id: "cmb-detection",
        label: "Cosmic microwave background detection",
        dateLabel: "1965",
        people: ["Arno Penzias", "Robert Wilson"],
        summary: "A pervasive microwave signal matched a major prediction of a hot early phase.",
      },
    ],
    evidence: [
      {
        id: "cmb-pattern",
        label: "Cosmic microwave background",
        summary: "Its near-uniform thermal spectrum and small anisotropies preserve information from the young universe.",
        sourceId: "atlas-lab:early-universe-cmb",
      },
      {
        id: "primordial-abundances",
        label: "Primordial light-element abundances",
        summary: "Observed hydrogen, helium, and related abundances constrain early-universe conditions.",
        sourceId: "atlas-lab:early-universe-abundances",
      },
    ],
    visual: { side: "center", depth: 0, emphasis: "primary" },
  },
  {
    id: "expansion-and-cooling",
    title: "Expansion and cooling",
    aliases: ["cosmic expansion", "thermal history"],
    kind: "process",
    scale: "cosmic",
    stageId: "early-universe",
    primaryParentId: "early-universe",
    displayOrder: 1,
    summary: "As the universe expanded, its average temperature and density fell, changing which structures could persist.",
    tags: ["formation", "temperature", "density"],
    formation: {
      prerequisites: ["a hot, dense expanding state"],
      transition: "Falling temperature reduced destructive collisions and opened successive stability windows.",
      newlyPossible: ["stable nuclei", "neutral matter", "gravitational growth"],
    },
    visual: { side: "left", depth: 1, emphasis: "secondary" },
  },
  {
    id: "primordial-plasma",
    title: "Primordial plasma",
    aliases: ["ionized early matter", "photon-baryon plasma"],
    kind: "entity",
    scale: "cosmic",
    stageId: "early-universe",
    primaryParentId: "early-universe",
    displayOrder: 2,
    summary: "Charged particles and radiation interacted frequently before neutral atoms could remain intact.",
    tags: ["structure", "radiation", "ionized matter"],
    formation: {
      prerequisites: ["energetic particles", "high temperature", "electromagnetic interaction"],
      transition: "Matter remained ionized while energetic photons repeatedly separated electrons from nuclei.",
      newlyPossible: ["acoustic patterns", "a later recombination transition", "fossil radiation signatures"],
    },
    structure: { parts: ["free electrons", "atomic nuclei", "photons"], systems: ["tightly coupled radiation and matter"] },
    visual: { side: "right", depth: 1, emphasis: "secondary" },
  },
  {
    id: "cosmic-microwave-background",
    title: "Cosmic microwave background",
    aliases: ["CMB", "relic radiation", "afterglow of the Big Bang"],
    kind: "event",
    scale: "cosmic",
    stageId: "early-universe",
    primaryParentId: "early-universe",
    displayOrder: 3,
    summary: "Relic radiation provides a measurable record of conditions near the transition to neutral matter.",
    tags: ["evidence", "observation", "microwave"],
    formation: {
      prerequisites: ["a hot radiative phase", "expansion", "the formation of neutral atoms"],
      transition: "Once photons scattered less often, radiation traveled freely and was stretched to microwave wavelengths.",
      newlyPossible: ["precision tests of cosmological models", "maps of early density variation", "estimates of cosmic parameters"],
    },
    evidence: [
      {
        id: "thermal-spectrum",
        label: "Near-perfect thermal spectrum",
        summary: "The measured spectrum is a stringent record of an earlier hot, equilibrated phase.",
        sourceId: "atlas-lab:cmb-thermal-spectrum",
      },
    ],
    visual: { side: "left", depth: 2, emphasis: "context" },
  },
  {
    id: "fundamental-forces-and-particles",
    title: "Forces and particles",
    aliases: ["fundamental interactions", "particle physics", "elementary particles"],
    kind: "stage",
    scale: "cosmic",
    stageId: "fundamental-forces-and-particles",
    primaryParentId: "early-universe",
    displayOrder: 0,
    time: { label: "The first fractions of a second onward", startYearsAgo: 13_800_000_000, precision: "approximate" },
    summary: "The map treats known interactions as physical boundary conditions and follows how cooling allowed durable particle populations; it does not assert that the laws themselves were created by the hot Big Bang.",
    tags: ["physics", "interactions", "particles", "standard model"],
    formation: {
      prerequisites: ["the hot early universe", "physical interactions treated as given boundary conditions"],
      transition: "Changing energy conditions altered which particles could persist and combine.",
      newlyPossible: ["protons and neutrons", "atomic nuclei", "electrically bound matter"],
    },
    structure: {
      parts: ["quarks", "leptons", "interaction carriers"],
      systems: ["quantum fields", "strong interaction", "electromagnetic interaction", "weak interaction", "gravity"],
    },
    discovery: [
      {
        id: "scattering-programs",
        label: "Scattering and accelerator programs",
        dateLabel: "20th century",
        summary: "Controlled high-energy collisions revealed a layered particle structure and regular interaction patterns.",
      },
      {
        id: "standard-model-synthesis",
        label: "Standard Model synthesis",
        dateLabel: "1960s–1970s",
        summary: "Multiple theories and experiments converged on a shared framework for known non-gravitational particles and interactions.",
      },
    ],
    evidence: [
      {
        id: "collision-signatures",
        label: "Repeatable collision signatures",
        summary: "Detector tracks, energies, and decay products follow stable quantitative patterns.",
        sourceId: "atlas-lab:particle-collision-signatures",
      },
      {
        id: "precision-predictions",
        label: "Precision agreement",
        summary: "Independent measurements agree closely with many particle-model predictions.",
        sourceId: "atlas-lab:particle-precision-tests",
      },
    ],
    visual: { side: "center", depth: 0, emphasis: "primary" },
  },
  {
    id: "particle-stabilization",
    title: "Particle stabilization",
    aliases: ["particle freeze-out", "stable matter ingredients"],
    kind: "process",
    scale: "cosmic",
    stageId: "fundamental-forces-and-particles",
    primaryParentId: "fundamental-forces-and-particles",
    displayOrder: 1,
    summary: "Falling energies allowed some particle populations and composite nuclei to persist.",
    tags: ["formation", "cooling", "nucleons"],
    formation: {
      prerequisites: ["expansion and cooling", "particle interactions", "small matter excess"],
      transition: "Creation, annihilation, decay, and binding ceased balancing in the same way as temperatures fell.",
      newlyPossible: ["persistent matter", "light nuclei", "later atoms"],
    },
    visual: { side: "left", depth: 1, emphasis: "secondary" },
  },
  {
    id: "quarks-and-leptons",
    title: "Quarks and leptons",
    aliases: ["elementary fermions", "matter particles"],
    kind: "entity",
    scale: "molecular",
    stageId: "fundamental-forces-and-particles",
    primaryParentId: "fundamental-forces-and-particles",
    displayOrder: 2,
    summary: "Two broad particle families supply the known elementary constituents of ordinary matter.",
    tags: ["structure", "quarks", "electrons", "neutrinos"],
    formation: {
      prerequisites: ["quantum fields", "interaction rules", "sufficiently low energies for durable populations"],
      transition: "Quarks became confined in composite particles while electrons remained stable elementary constituents.",
      newlyPossible: ["nuclei", "electron shells", "ordinary matter"],
    },
    structure: { parts: ["quarks", "charged leptons", "neutrinos"], systems: ["particle generations", "interaction charges"] },
    visual: { side: "right", depth: 1, emphasis: "secondary" },
  },
  {
    id: "particle-collision-traces",
    title: "Particle collision traces",
    aliases: ["accelerator evidence", "detector events"],
    kind: "event",
    scale: "technological",
    stageId: "fundamental-forces-and-particles",
    primaryParentId: "fundamental-forces-and-particles",
    displayOrder: 3,
    summary: "Instrumented collisions turn otherwise invisible interactions into reconstructable tracks and energy deposits.",
    tags: ["evidence", "accelerators", "detectors"],
    formation: {
      prerequisites: ["particle beams", "precision detectors", "conservation laws", "statistical analysis"],
      transition: "Controlled collisions produced repeatable event patterns that could be compared with quantitative models.",
      newlyPossible: ["particle identification", "interaction tests", "searches for rare processes"],
    },
    evidence: [
      {
        id: "event-reconstruction",
        label: "Reconstructed detector events",
        summary: "Independent detector layers jointly constrain charge, momentum, energy, and decay paths.",
        sourceId: "atlas-lab:particle-event-reconstruction",
      },
    ],
    visual: { side: "left", depth: 2, emphasis: "context" },
  },
  {
    id: "atoms",
    title: "Atoms",
    aliases: ["atomic matter", "neutral atoms", "recombination era"],
    kind: "stage",
    scale: "molecular",
    stageId: "atoms",
    primaryParentId: "fundamental-forces-and-particles",
    displayOrder: 0,
    time: { label: "About 380,000 years after the Big Bang", startYearsAgo: 13_799_620_000, precision: "approximate" },
    summary: "Cooling allowed electrons to remain bound to nuclei, producing neutral atoms and a transparent universe.",
    tags: ["chemistry", "matter", "recombination", "hydrogen"],
    formation: {
      prerequisites: ["atomic nuclei", "electrons", "temperatures low enough for stable binding"],
      transition: "Electromagnetic attraction held electrons in quantized states around nuclei faster than radiation could ionize them.",
      newlyPossible: ["neutral gas", "atomic spectra", "chemical bonding"],
    },
    structure: {
      parts: ["a compact nucleus", "bound electrons"],
      systems: ["electron energy levels", "electromagnetic binding", "isotopes"],
    },
    discovery: [
      {
        id: "atomic-theory-development",
        label: "Atomic theory develops",
        dateLabel: "19th–early 20th centuries",
        people: ["John Dalton", "J. J. Thomson", "Ernest Rutherford", "Niels Bohr"],
        summary: "Successive models linked chemical regularity, electrons, nuclei, and quantized spectra.",
      },
    ],
    evidence: [
      {
        id: "spectral-lines",
        label: "Discrete spectral lines",
        summary: "Atoms absorb and emit characteristic wavelengths tied to quantized energy differences.",
        sourceId: "atlas-lab:atomic-spectral-lines",
      },
      {
        id: "scattering-patterns",
        label: "Scattering patterns",
        summary: "Deflection experiments reveal concentrated nuclei and surrounding electron-scale structure.",
        sourceId: "atlas-lab:atomic-scattering",
      },
    ],
    visual: { side: "center", depth: 0, emphasis: "primary" },
  },
  {
    id: "recombination",
    title: "Recombination",
    aliases: ["photon decoupling", "neutral atom formation"],
    kind: "process",
    scale: "cosmic",
    stageId: "atoms",
    primaryParentId: "atoms",
    displayOrder: 1,
    summary: "Electrons and nuclei formed stable neutral atoms as the cosmic plasma cooled.",
    tags: ["formation", "hydrogen", "transparency"],
    formation: {
      prerequisites: ["free electrons", "atomic nuclei", "continued expansion and cooling"],
      transition: "Bound states survived ionizing radiation in large numbers.",
      newlyPossible: ["transparent space", "neutral hydrogen clouds", "unimpeded background radiation"],
    },
    visual: { side: "left", depth: 1, emphasis: "secondary" },
  },
  {
    id: "atomic-structure",
    title: "Nuclei and electron shells",
    aliases: ["atomic structure", "electron cloud", "nucleus"],
    kind: "entity",
    scale: "molecular",
    stageId: "atoms",
    primaryParentId: "atoms",
    displayOrder: 2,
    summary: "A dense nucleus and quantized electron states give each element its characteristic behavior.",
    tags: ["structure", "nucleus", "electron shell", "isotope"],
    formation: {
      prerequisites: ["protons and neutrons", "electrons", "electromagnetic attraction"],
      transition: "Nuclear composition fixed elemental identity while electrons occupied allowed bound states.",
      newlyPossible: ["element-specific spectra", "ions", "chemical valence"],
    },
    structure: { parts: ["protons", "neutrons", "electrons"], systems: ["nucleus", "electron shells", "isotopes"] },
    visual: { side: "right", depth: 1, emphasis: "secondary" },
  },
  {
    id: "atomic-theory-milestones",
    title: "Atomic theory milestones",
    aliases: ["Dalton model", "Rutherford model", "Bohr atom"],
    kind: "event",
    scale: "technological",
    stageId: "atoms",
    primaryParentId: "atoms",
    displayOrder: 3,
    summary: "Chemistry, scattering, and spectroscopy successively exposed the atom's internal organization.",
    tags: ["discovery", "history of science", "models"],
    formation: {
      prerequisites: ["quantitative chemistry", "vacuum tubes", "scattering experiments", "spectroscopy"],
      transition: "Models were revised as new measurements contradicted indivisible or diffuse pictures of matter.",
      newlyPossible: ["nuclear models", "quantum atomic theory", "predictive chemistry"],
    },
    discovery: [
      {
        id: "nuclear-atom",
        label: "The nuclear atom",
        dateLabel: "1911",
        people: ["Ernest Rutherford"],
        summary: "Large-angle scattering supported a compact, positively charged nucleus.",
      },
    ],
    visual: { side: "left", depth: 2, emphasis: "context" },
  },
  {
    id: "stars-and-heavy-elements",
    title: "Stars and heavy elements",
    aliases: ["stellar evolution", "stellar nucleosynthesis", "element factories"],
    kind: "stage",
    scale: "stellar",
    stageId: "stars-and-heavy-elements",
    primaryParentId: "atoms",
    displayOrder: 0,
    time: { label: "First stars roughly 100–200 million years after the Big Bang", startYearsAgo: 13_600_000_000, precision: "approximate" },
    summary: "Gravity concentrated mostly hydrogen and helium until fusion ignited, powering stars and building new nuclei.",
    tags: ["astronomy", "fusion", "nucleosynthesis", "stellar evolution"],
    formation: {
      prerequisites: ["neutral gas", "gravity", "density variation", "radiative cooling"],
      transition: "Collapsing gas heated and compressed until sustained nuclear fusion balanced gravitational contraction.",
      newlyPossible: ["starlight", "heavy-element production", "enriched stellar remnants"],
    },
    structure: {
      parts: ["fusion core", "radiative or convective layers", "stellar atmosphere"],
      systems: ["hydrostatic balance", "energy transport", "stellar life cycles"],
    },
    discovery: [
      {
        id: "stellar-composition",
        label: "Stellar composition decoded",
        dateLabel: "1920s",
        people: ["Cecilia Payne-Gaposchkin"],
        summary: "Spectral analysis established that stars are dominated by hydrogen and helium.",
      },
      {
        id: "nucleosynthesis-framework",
        label: "Stellar nucleosynthesis framework",
        dateLabel: "Mid-20th century",
        summary: "Nuclear physics and stellar observations connected element production to stellar interiors and explosions.",
      },
    ],
    evidence: [
      {
        id: "stellar-spectra",
        label: "Stellar spectra",
        summary: "Absorption and emission lines identify composition, temperature, motion, and ionization.",
        sourceId: "atlas-lab:stellar-spectra",
      },
      {
        id: "element-abundance-patterns",
        label: "Element abundance patterns",
        summary: "Measured abundance families track distinct nuclear pathways and stellar events.",
        sourceId: "atlas-lab:stellar-abundances",
      },
    ],
    visual: { side: "center", depth: 0, emphasis: "primary" },
  },
  {
    id: "stellar-fusion",
    title: "Stellar fusion",
    aliases: ["nuclear fusion", "hydrogen burning", "stellar ignition"],
    kind: "process",
    scale: "stellar",
    stageId: "stars-and-heavy-elements",
    primaryParentId: "stars-and-heavy-elements",
    displayOrder: 1,
    summary: "Extreme pressure and temperature let light nuclei combine, releasing energy and making heavier nuclei.",
    tags: ["formation", "fusion", "energy"],
    formation: {
      prerequisites: ["gravitational collapse", "dense stellar cores", "light nuclei"],
      transition: "Fusion reactions released energy and supported long-lived luminous stars against collapse.",
      newlyPossible: ["stable stellar lifetimes", "successive fusion stages", "heavy-element production"],
    },
    visual: { side: "left", depth: 1, emphasis: "secondary" },
  },
  {
    id: "heavy-elements",
    title: "Heavy elements",
    aliases: ["metals", "elements beyond helium", "stellar ash"],
    kind: "entity",
    scale: "molecular",
    stageId: "stars-and-heavy-elements",
    primaryParentId: "stars-and-heavy-elements",
    displayOrder: 2,
    summary: "Stellar fusion and energetic stellar events produced and dispersed nuclei beyond hydrogen and helium.",
    tags: ["structure", "elements", "carbon", "oxygen", "iron"],
    formation: {
      prerequisites: ["stellar fusion", "neutron-capture pathways", "stellar mass loss and explosions"],
      transition: "Multiple nuclear pathways assembled heavier nuclei and returned enriched material to interstellar space.",
      newlyPossible: ["rocky minerals", "complex chemistry", "metal-rich later stars and planets"],
    },
    structure: { parts: ["carbon", "oxygen", "silicon", "iron-group elements"], systems: ["periodic families", "nuclear abundance pathways"] },
    visual: { side: "right", depth: 1, emphasis: "secondary" },
  },
  {
    id: "stellar-spectroscopy",
    title: "Stellar spectroscopy",
    aliases: ["star spectra", "spectral fingerprints"],
    kind: "technology",
    scale: "technological",
    stageId: "stars-and-heavy-elements",
    primaryParentId: "stars-and-heavy-elements",
    displayOrder: 3,
    summary: "Dispersing starlight into spectra lets observers infer the otherwise inaccessible conditions inside and around stars.",
    tags: ["evidence", "discovery", "astronomy"],
    formation: {
      prerequisites: ["optics", "atomic spectra", "precise wavelength measurement"],
      transition: "Characteristic spectral lines linked laboratory elements to astronomical light.",
      newlyPossible: ["remote chemical analysis", "stellar classification", "measurements of motion and temperature"],
    },
    evidence: [
      {
        id: "spectral-fingerprints",
        label: "Element-specific line patterns",
        summary: "Laboratory and stellar line patterns match at the same characteristic wavelengths.",
        sourceId: "atlas-lab:stellar-spectral-fingerprints",
      },
    ],
    visual: { side: "left", depth: 2, emphasis: "context" },
  },
  {
    id: "planetary-systems",
    title: "Planetary systems",
    aliases: ["solar systems", "exoplanet systems", "world systems"],
    kind: "stage",
    scale: "planetary",
    stageId: "planetary-systems",
    primaryParentId: "stars-and-heavy-elements",
    displayOrder: 0,
    time: { label: "Our Solar System formed about 4.6 billion years ago", startYearsAgo: 4_600_000_000, precision: "approximate" },
    summary: "Gas, ice, dust, and rock in rotating stellar disks accumulated into dynamically organized systems of worlds.",
    tags: ["planets", "orbits", "accretion", "exoplanets"],
    formation: {
      prerequisites: ["long-lived stars", "heavy elements", "rotating protoplanetary disks"],
      transition: "Dust and ice aggregated, larger bodies accreted material, and gravity sorted surviving orbits.",
      newlyPossible: ["rocky planets", "giant planets", "moons and small-body reservoirs"],
    },
    structure: {
      parts: ["host star", "planets", "moons", "asteroids and comets"],
      systems: ["orbital resonances", "debris reservoirs", "disk chemistry"],
    },
    discovery: [
      {
        id: "heliocentric-reframing",
        label: "Heliocentric system",
        dateLabel: "16th–17th centuries",
        people: ["Nicolaus Copernicus", "Johannes Kepler", "Galileo Galilei"],
        summary: "Geometric models and telescopic observations reorganized the known planets around the Sun.",
      },
      {
        id: "exoplanet-era",
        label: "Exoplanet era",
        dateLabel: "1990s onward",
        summary: "Multiple detection methods revealed that planetary systems are common and diverse.",
      },
    ],
    evidence: [
      {
        id: "disk-images",
        label: "Protoplanetary disk images",
        summary: "Young stars are observed with structured disks, gaps, rings, and planet-forming material.",
        sourceId: "atlas-lab:protoplanetary-disks",
      },
      {
        id: "orbital-signals",
        label: "Repeatable orbital signals",
        summary: "Transits, stellar motion, and direct imaging reveal planets following predictable orbits.",
        sourceId: "atlas-lab:exoplanet-orbits",
      },
    ],
    visual: { side: "center", depth: 0, emphasis: "primary" },
  },
  {
    id: "planetary-accretion",
    title: "Planetary accretion",
    aliases: ["planet formation", "planetesimal growth"],
    kind: "process",
    scale: "planetary",
    stageId: "planetary-systems",
    primaryParentId: "planetary-systems",
    displayOrder: 1,
    summary: "Small grains became pebbles, planetesimals, and eventually worlds through collisions and gravity.",
    tags: ["formation", "disk", "gravity"],
    formation: {
      prerequisites: ["dust and ice", "a rotating disk", "collisions", "gravity"],
      transition: "Growth became increasingly gravitational as some bodies accumulated more mass than their neighbors.",
      newlyPossible: ["differentiated worlds", "atmosphere retention", "long-lived orbital niches"],
    },
    visual: { side: "left", depth: 1, emphasis: "secondary" },
  },
  {
    id: "planetary-architecture",
    title: "Stars, worlds, and smaller bodies",
    aliases: ["planetary architecture", "orbital system"],
    kind: "entity",
    scale: "planetary",
    stageId: "planetary-systems",
    primaryParentId: "planetary-systems",
    displayOrder: 2,
    summary: "A planetary system is a nested dynamical structure rather than a random collection of worlds.",
    tags: ["structure", "orbits", "moons", "comets"],
    formation: {
      prerequisites: ["accretion", "orbital migration", "gravitational scattering"],
      transition: "Interactions removed, rearranged, or stabilized bodies until a persistent architecture remained.",
      newlyPossible: ["stable seasons and climates", "impact delivery", "tidal relationships"],
    },
    structure: { parts: ["host star", "rocky worlds", "giant planets", "moons", "small bodies"], systems: ["orbits", "resonances", "debris belts"] },
    visual: { side: "right", depth: 1, emphasis: "secondary" },
  },
  {
    id: "exoplanet-discovery",
    title: "Exoplanet discovery",
    aliases: ["planet transit", "radial velocity", "51 Pegasi b"],
    kind: "event",
    scale: "technological",
    stageId: "planetary-systems",
    primaryParentId: "planetary-systems",
    displayOrder: 3,
    summary: "Precision measurements made planetary systems beyond the Sun empirically visible.",
    tags: ["discovery", "astronomy", "transit"],
    formation: {
      prerequisites: ["stable telescopes", "precision spectroscopy", "long observing campaigns"],
      transition: "Repeated dimming and stellar motion isolated the periodic influence of orbiting planets.",
      newlyPossible: ["comparative planetology", "population estimates", "atmospheric follow-up"],
    },
    discovery: [
      {
        id: "sunlike-star-exoplanet",
        label: "Planet around a Sun-like star",
        dateLabel: "1995",
        people: ["Michel Mayor", "Didier Queloz"],
        summary: "A periodic radial-velocity signal revealed 51 Pegasi b and accelerated the modern exoplanet field.",
      },
    ],
    visual: { side: "left", depth: 2, emphasis: "context" },
  },
  {
    id: "earth",
    title: "Earth",
    aliases: ["home planet", "terrestrial Earth", "Gaia"],
    kind: "stage",
    scale: "planetary",
    stageId: "earth",
    primaryParentId: "planetary-systems",
    displayOrder: 0,
    time: { label: "About 4.54 billion years ago", startYearsAgo: 4_540_000_000, precision: "approximate" },
    summary: "Accretion, differentiation, cooling, water, atmosphere, and long-running geochemical cycles produced a dynamic rocky world.",
    tags: ["geology", "planet", "ocean", "atmosphere", "plate tectonics"],
    formation: {
      prerequisites: ["rocky planetary material", "a persistent orbit", "volatile delivery and retention", "internal heat"],
      transition: "Accretion and differentiation built layers while cooling and cycling established coupled surface systems.",
      newlyPossible: ["stable liquid-water environments", "mineral diversity", "long-lived chemical gradients"],
    },
    structure: {
      parts: ["metallic core", "silicate mantle", "crust", "ocean", "atmosphere"],
      systems: ["plate tectonics", "water cycle", "carbon cycle", "magnetic field"],
    },
    discovery: [
      {
        id: "deep-time",
        label: "Deep geological time",
        dateLabel: "18th–20th centuries",
        summary: "Stratigraphy, fossils, and radiometric clocks established a history far older than recorded civilization.",
      },
      {
        id: "plate-tectonic-synthesis",
        label: "Plate-tectonic synthesis",
        dateLabel: "Mid-20th century",
        summary: "Seafloor, earthquake, magnetic, and continental evidence converged on moving lithospheric plates.",
      },
    ],
    evidence: [
      {
        id: "radiometric-ages",
        label: "Radiometric ages",
        summary: "Multiple isotope systems provide cross-checking numerical constraints on rocks and planetary materials.",
        sourceId: "atlas-lab:earth-radiometric-ages",
      },
      {
        id: "seismic-interior",
        label: "Seismic wave paths",
        summary: "Wave travel and shadow zones reveal a layered planetary interior.",
        sourceId: "atlas-lab:earth-seismic-structure",
      },
    ],
    visual: { side: "center", depth: 0, emphasis: "primary" },
  },
  {
    id: "plate-tectonics",
    title: "Plate tectonics",
    aliases: ["continental drift", "seafloor spreading", "mobile lithosphere"],
    kind: "process",
    scale: "geological",
    stageId: "earth",
    primaryParentId: "earth",
    displayOrder: 1,
    summary: "Earth's outer shell is divided into moving plates that recycle crust and reshape the surface.",
    tags: ["formation", "geology", "continents", "volcanoes"],
    formation: {
      prerequisites: ["a layered rocky planet", "internal heat", "a mechanically active mantle and lithosphere"],
      transition: "Heat loss and buoyancy drove long-term deformation, spreading, subduction, and plate motion.",
      newlyPossible: ["continental cycles", "mountain building", "material exchange between surface and interior"],
    },
    visual: { side: "left", depth: 1, emphasis: "secondary" },
  },
  {
    id: "earth-systems",
    title: "Core, mantle, crust, ocean, atmosphere",
    aliases: ["Earth systems", "geospheres", "planetary layers"],
    kind: "entity",
    scale: "geological",
    stageId: "earth",
    primaryParentId: "earth",
    displayOrder: 2,
    summary: "Earth's layers and surface reservoirs exchange energy and material across many timescales.",
    tags: ["structure", "geosphere", "hydrosphere", "atmosphere"],
    formation: {
      prerequisites: ["planetary differentiation", "cooling", "volatile cycling"],
      transition: "Materials separated by density and phase while impacts, volcanism, and condensation built surface reservoirs.",
      newlyPossible: ["weather", "ocean circulation", "geochemical feedbacks"],
    },
    structure: { parts: ["core", "mantle", "crust", "ocean", "atmosphere"], systems: ["climate", "tectonics", "hydrologic cycle"] },
    visual: { side: "right", depth: 1, emphasis: "secondary" },
  },
  {
    id: "deep-time-geoscience",
    title: "Reading deep time",
    aliases: ["geochronology", "stratigraphy", "Earth history"],
    kind: "event",
    scale: "technological",
    stageId: "earth",
    primaryParentId: "earth",
    displayOrder: 3,
    summary: "Layered rocks, fossils, magnetic patterns, and isotopic clocks make Earth's otherwise inaccessible history reconstructable.",
    tags: ["discovery", "evidence", "geology"],
    formation: {
      prerequisites: ["mapped strata", "fossil succession", "radioactivity", "laboratory measurement"],
      transition: "Relative sequences were joined to quantitative clocks and global physical mechanisms.",
      newlyPossible: ["dated Earth history", "plate reconstructions", "tests of climate and extinction hypotheses"],
    },
    discovery: [
      {
        id: "continental-drift-to-plates",
        label: "Continental drift to plate tectonics",
        dateLabel: "1912–1960s",
        people: ["Alfred Wegener"],
        summary: "A disputed continental-drift proposal became a mechanistic theory as new ocean-floor evidence accumulated.",
      },
    ],
    visual: { side: "left", depth: 2, emphasis: "context" },
  },
  {
    id: "life",
    title: "Life",
    aliases: ["living systems", "first life", "abiogenesis"],
    kind: "stage",
    scale: "biological",
    stageId: "life",
    primaryParentId: "earth",
    displayOrder: 0,
    time: { label: "At least about 3.5 billion years ago", startYearsAgo: 3_500_000_000, precision: "approximate" },
    summary: "Some chemical systems became bounded, self-maintaining, heritable, and subject to selection; the exact historical pathway remains unresolved.",
    tags: ["biology", "cells", "metabolism", "heredity", "evolution"],
    formation: {
      prerequisites: ["liquid environments", "usable energy gradients", "carbon-rich chemistry", "molecular compartmentalization"],
      transition: "Networks of reactions, boundaries, and information-bearing molecules became coupled closely enough to persist and reproduce with variation.",
      newlyPossible: ["cells", "evolution by selection", "ecosystems"],
    },
    structure: {
      parts: ["boundary", "metabolic network", "hereditary information", "molecular machinery"],
      systems: ["homeostasis", "replication", "variation and selection"],
    },
    discovery: [
      {
        id: "cell-observation",
        label: "Cells become visible",
        dateLabel: "17th century",
        people: ["Robert Hooke", "Antonie van Leeuwenhoek"],
        summary: "Microscopy exposed cellular and microbial organization beyond unaided vision.",
      },
      {
        id: "evolutionary-theory",
        label: "Evolution by natural selection",
        dateLabel: "1858–1859",
        people: ["Charles Darwin", "Alfred Russel Wallace"],
        summary: "A general mechanism connected inherited variation, differential reproduction, and adaptation.",
      },
    ],
    evidence: [
      {
        id: "shared-biochemistry",
        label: "Shared biochemical machinery",
        summary: "Cells across life use deeply related genetic, metabolic, and translational systems.",
        sourceId: "atlas-lab:life-shared-biochemistry",
      },
      {
        id: "fossil-genetic-convergence",
        label: "Fossil and genetic convergence",
        summary: "Independent historical records support descent with modification across immense timescales.",
        sourceId: "atlas-lab:life-fossil-genetic-record",
      },
    ],
    visual: { side: "center", depth: 0, emphasis: "primary" },
  },
  {
    id: "evolution-by-selection",
    title: "Evolution by selection",
    aliases: ["natural selection", "Darwinian evolution", "descent with modification"],
    kind: "process",
    scale: "biological",
    stageId: "life",
    primaryParentId: "life",
    displayOrder: 1,
    summary: "Heritable variation and unequal reproductive success alter populations across generations.",
    tags: ["formation", "variation", "selection", "adaptation"],
    formation: {
      prerequisites: ["replication", "heritable variation", "limited resources", "differential reproduction"],
      transition: "Variants left different numbers of descendants, accumulating population-level change.",
      newlyPossible: ["adaptation", "diversification", "complex ecological relationships"],
    },
    visual: { side: "left", depth: 1, emphasis: "secondary" },
  },
  {
    id: "cells",
    title: "Cells",
    aliases: ["cellular life", "prokaryotic cells", "cell membrane"],
    kind: "entity",
    scale: "biological",
    stageId: "life",
    primaryParentId: "life",
    displayOrder: 2,
    summary: "Membrane-bounded cells couple chemistry, information, energy use, and reproduction in one persistent unit.",
    tags: ["structure", "membrane", "genome", "metabolism"],
    formation: {
      prerequisites: ["compartments", "catalytic networks", "hereditary molecules", "energy capture"],
      transition: "Boundaries kept cooperative reactions together while regulated exchange sustained them.",
      newlyPossible: ["cell lineages", "specialized internal machinery", "multicellular cooperation"],
    },
    structure: { parts: ["membrane", "cytoplasm", "genetic material", "molecular machines"], systems: ["metabolism", "regulation", "division"] },
    visual: { side: "right", depth: 1, emphasis: "secondary" },
  },
  {
    id: "microscopy-and-evolutionary-theory",
    title: "Microscopy and evolutionary theory",
    aliases: ["cell theory", "history of biology", "Darwin and Wallace"],
    kind: "event",
    scale: "technological",
    stageId: "life",
    primaryParentId: "life",
    displayOrder: 3,
    summary: "New instruments and population-level reasoning made life's organization and historical change scientifically tractable.",
    tags: ["discovery", "microscope", "evolution"],
    formation: {
      prerequisites: ["optical instruments", "comparative anatomy", "biogeography", "breeding observations"],
      transition: "Direct observation of cells joined an explanatory framework for inherited population change.",
      newlyPossible: ["cell biology", "common-descent tests", "modern evolutionary synthesis"],
    },
    discovery: [
      {
        id: "cell-theory",
        label: "Cell theory",
        dateLabel: "19th century",
        summary: "Accumulated observations supported the cell as a fundamental unit of organisms.",
      },
    ],
    visual: { side: "left", depth: 2, emphasis: "context" },
  },
  {
    id: "multicellular-life",
    title: "Multicellular life",
    aliases: ["complex multicellularity", "many-celled organisms"],
    kind: "stage",
    scale: "organismal",
    stageId: "multicellular-life",
    primaryParentId: "life",
    displayOrder: 0,
    time: { label: "Complex forms diversified strongly around 600 million years ago", startYearsAgo: 600_000_000, precision: "approximate" },
    summary: "Cells formed durable cooperative collectives, divided labor, and built bodies with coordinated development.",
    tags: ["organisms", "development", "tissues", "specialization"],
    formation: {
      prerequisites: ["cells", "adhesion", "cell communication", "cooperation and conflict control"],
      transition: "Cell lineages remained together, coordinated growth, and differentiated into complementary roles.",
      newlyPossible: ["tissues and organs", "large mobile bodies", "new ecological strategies"],
    },
    structure: {
      parts: ["specialized cells", "tissues", "organs", "body plans"],
      systems: ["development", "cell signaling", "resource transport", "immune coordination"],
    },
    discovery: [
      {
        id: "developmental-cell-lineage",
        label: "Development and cell lineage",
        dateLabel: "19th–21st centuries",
        summary: "Embryology, microscopy, and genetics connected adult structures to coordinated cell differentiation.",
      },
      {
        id: "ediacaran-record",
        label: "Ediacaran fossil record",
        dateLabel: "Late 19th century onward",
        summary: "Fossil assemblages revealed complex organisms before the Cambrian diversification.",
      },
    ],
    evidence: [
      {
        id: "developmental-genetics",
        label: "Shared developmental toolkits",
        summary: "Related regulatory genes pattern widely different multicellular bodies.",
        sourceId: "atlas-lab:multicellular-developmental-genetics",
      },
      {
        id: "multicellular-fossils",
        label: "Multicellular fossil sequences",
        summary: "Fossils constrain when body plans, tissues, and ecological roles became established.",
        sourceId: "atlas-lab:multicellular-fossil-record",
      },
    ],
    visual: { side: "center", depth: 0, emphasis: "primary" },
  },
  {
    id: "cell-specialization",
    title: "Cell specialization",
    aliases: ["cell differentiation", "division of labor"],
    kind: "process",
    scale: "organismal",
    stageId: "multicellular-life",
    primaryParentId: "multicellular-life",
    displayOrder: 1,
    summary: "Cells with the same inherited genome adopted different stable roles through regulated gene activity.",
    tags: ["formation", "development", "differentiation"],
    formation: {
      prerequisites: ["cell communication", "gene regulation", "adhesion", "reliable development"],
      transition: "Position and signals drove distinct gene-expression programs within one growing body.",
      newlyPossible: ["tissues", "organs", "coordinated body functions"],
    },
    visual: { side: "left", depth: 1, emphasis: "secondary" },
  },
  {
    id: "tissues-and-organs",
    title: "Tissues, organs, and body plans",
    aliases: ["organ systems", "multicellular structure", "body plan"],
    kind: "entity",
    scale: "organismal",
    stageId: "multicellular-life",
    primaryParentId: "multicellular-life",
    displayOrder: 2,
    summary: "Nested layers of specialized cells perform coordinated functions that no isolated cell can sustain.",
    tags: ["structure", "tissues", "organs", "development"],
    formation: {
      prerequisites: ["specialized cells", "structural support", "transport", "developmental patterning"],
      transition: "Stable tissue arrangements integrated local cell work into whole-organism functions.",
      newlyPossible: ["larger bodies", "specialized movement and digestion", "centralized sensing"],
    },
    structure: { parts: ["specialized cells", "tissues", "organs"], systems: ["circulation", "digestion", "movement", "development"] },
    visual: { side: "right", depth: 1, emphasis: "secondary" },
  },
  {
    id: "multicellular-fossil-record",
    title: "The multicellular fossil record",
    aliases: ["Ediacaran fossils", "Cambrian fossils", "body-plan fossils"],
    kind: "event",
    scale: "geological",
    stageId: "multicellular-life",
    primaryParentId: "multicellular-life",
    displayOrder: 3,
    summary: "Preserved bodies, traces, and chemical signals constrain the timing and ecology of complex life.",
    tags: ["evidence", "fossils", "paleontology"],
    formation: {
      prerequisites: ["multicellular organisms", "burial or mineralization", "preservable structures", "dated strata"],
      transition: "Biological structures or activity left durable traces that survived later geological change.",
      newlyPossible: ["body-plan comparisons", "dated diversification sequences", "ecosystem reconstructions"],
    },
    evidence: [
      {
        id: "body-and-trace-fossils",
        label: "Body and trace fossils",
        summary: "Anatomical remains and behavior traces provide complementary records of organismal complexity.",
        sourceId: "atlas-lab:multicellular-body-trace-fossils",
      },
    ],
    visual: { side: "left", depth: 2, emphasis: "context" },
  },
  {
    id: "nervous-systems",
    title: "Nervous systems",
    aliases: ["neural systems", "brains and nerves", "sensory-motor systems"],
    kind: "stage",
    scale: "organismal",
    stageId: "nervous-systems",
    primaryParentId: "multicellular-life",
    displayOrder: 0,
    time: { label: "Early animal nervous systems more than 500 million years ago", startYearsAgo: 550_000_000, precision: "approximate" },
    summary: "Specialized excitable cells linked distant sensors and effectors, enabling fast integrated control of behavior.",
    tags: ["neuroscience", "neurons", "brain", "behavior", "sensing"],
    formation: {
      prerequisites: ["multicellular bodies", "excitable cells", "cell signaling", "movable effectors and sensors"],
      transition: "Long-range electrical and chemical signaling coordinated information across the body.",
      newlyPossible: ["integrated perception", "learning and memory", "adaptive action"],
    },
    structure: {
      parts: ["sensory receptors", "neurons", "synapses", "support cells", "effectors"],
      systems: ["sensory pathways", "central integration", "motor control", "plasticity"],
    },
    discovery: [
      {
        id: "bioelectricity",
        label: "Bioelectric signaling",
        dateLabel: "18th–19th centuries",
        people: ["Luigi Galvani"],
        summary: "Experiments connected nerve and muscle activity to electrical phenomena.",
      },
      {
        id: "neuron-doctrine",
        label: "Neuron doctrine",
        dateLabel: "Late 19th–early 20th centuries",
        people: ["Santiago Ramón y Cajal"],
        summary: "Microscopy supported discrete communicating cells rather than one continuous nerve net.",
      },
    ],
    evidence: [
      {
        id: "electrophysiology",
        label: "Electrophysiological recordings",
        summary: "Measured voltage changes track signal propagation, sensory input, and motor output.",
        sourceId: "atlas-lab:nervous-electrophysiology",
      },
      {
        id: "lesion-stimulation",
        label: "Lesion and stimulation patterns",
        summary: "Changing defined neural tissue produces reproducible changes in function and behavior.",
        sourceId: "atlas-lab:nervous-lesion-stimulation",
      },
    ],
    visual: { side: "center", depth: 0, emphasis: "primary" },
  },
  {
    id: "neural-signaling",
    title: "Neural signaling",
    aliases: ["action potentials", "synaptic transmission"],
    kind: "process",
    scale: "organismal",
    stageId: "nervous-systems",
    primaryParentId: "nervous-systems",
    displayOrder: 1,
    summary: "Electrical membrane events and chemical synapses carry and transform signals through living tissue.",
    tags: ["formation", "signal", "synapse", "plasticity"],
    formation: {
      prerequisites: ["ion gradients", "excitable membranes", "receptors", "cell junctions"],
      transition: "Cells converted local changes into propagating signals and passed them selectively to other cells.",
      newlyPossible: ["fast coordination", "distributed integration", "experience-dependent plasticity"],
    },
    visual: { side: "left", depth: 1, emphasis: "secondary" },
  },
  {
    id: "neurons-and-networks",
    title: "Neurons, synapses, and networks",
    aliases: ["neural network", "brain circuitry", "connectome"],
    kind: "entity",
    scale: "organismal",
    stageId: "nervous-systems",
    primaryParentId: "nervous-systems",
    displayOrder: 2,
    summary: "Interconnected excitable cells form circuits whose collective dynamics organize perception and action.",
    tags: ["structure", "neurons", "synapses", "circuits"],
    formation: {
      prerequisites: ["neurons", "synapses", "developmental wiring", "activity-dependent change"],
      transition: "Connection patterns and changing synaptic strengths shaped coordinated circuit responses.",
      newlyPossible: ["feature detection", "memory traces", "behavioral control"],
    },
    structure: { parts: ["neurons", "synapses", "glia"], systems: ["circuits", "pathways", "distributed networks"] },
    visual: { side: "right", depth: 1, emphasis: "secondary" },
  },
  {
    id: "neuron-doctrine",
    title: "The neuron doctrine",
    aliases: ["Cajal", "Golgi stain", "cellular neuroscience"],
    kind: "concept",
    scale: "technological",
    stageId: "nervous-systems",
    primaryParentId: "nervous-systems",
    displayOrder: 3,
    summary: "Improved staining and microscopy reframed nervous tissue as networks of discrete communicating cells.",
    tags: ["discovery", "history of neuroscience", "microscopy"],
    formation: {
      prerequisites: ["microscopy", "selective tissue staining", "comparative anatomy"],
      transition: "Visible cell boundaries and processes supported a cellular rather than fully continuous account.",
      newlyPossible: ["circuit mapping", "synaptic theory", "modern cellular neuroscience"],
    },
    discovery: [
      {
        id: "cajal-drawings",
        label: "Cajal's neural observations",
        dateLabel: "Late 19th century",
        people: ["Santiago Ramón y Cajal"],
        summary: "Careful preparations and drawings revealed recurring cellular structures and directional organization.",
      },
    ],
    visual: { side: "left", depth: 2, emphasis: "context" },
  },
  {
    id: "humans",
    title: "Humans",
    aliases: ["Homo sapiens", "human beings", "modern humans"],
    kind: "stage",
    scale: "cognitive",
    stageId: "humans",
    primaryParentId: "nervous-systems",
    displayOrder: 0,
    time: { label: "Homo sapiens about 300,000 years ago", startYearsAgo: 300_000, precision: "approximate" },
    summary: "An embodied social primate lineage combined dexterity, flexible cognition, teaching, language-ready communication, and cumulative cooperation.",
    tags: ["anthropology", "cognition", "social learning", "Homo sapiens"],
    formation: {
      prerequisites: ["primate bodies and nervous systems", "social groups", "ecological variability", "long juvenile learning"],
      transition: "Biological capacities and increasingly cumulative social learning co-evolved across many generations.",
      newlyPossible: ["symbolic communication", "rapid cultural adaptation", "large cooperative networks"],
    },
    structure: {
      parts: ["brain and body", "developmental life history", "social relationships"],
      systems: ["language-ready cognition", "cooperation", "tool use", "teaching"],
    },
    discovery: [
      {
        id: "human-fossil-record",
        label: "Human fossil record",
        dateLabel: "19th century onward",
        summary: "Fossils and artifacts placed human anatomy and behavior within a branching evolutionary history.",
      },
      {
        id: "ancient-genomics",
        label: "Ancient genomics",
        dateLabel: "21st century",
        summary: "Recovered DNA exposed migrations, population structure, and interbreeding among human lineages.",
      },
    ],
    evidence: [
      {
        id: "fossil-artifact-context",
        label: "Fossils in archaeological context",
        summary: "Dated remains and artifacts jointly constrain anatomy, behavior, and environment.",
        sourceId: "atlas-lab:human-fossil-artifact-context",
      },
      {
        id: "comparative-genomes",
        label: "Comparative and ancient genomes",
        summary: "Genetic relationships independently test population histories inferred from fossils.",
        sourceId: "atlas-lab:human-comparative-genomes",
      },
    ],
    visual: { side: "center", depth: 0, emphasis: "primary" },
  },
  {
    id: "cumulative-social-learning",
    title: "Cumulative social learning",
    aliases: ["teaching", "ratchet effect", "cultural learning"],
    kind: "process",
    scale: "cognitive",
    stageId: "humans",
    primaryParentId: "humans",
    displayOrder: 1,
    summary: "Skills and conventions were copied, taught, modified, and retained instead of repeatedly reinvented.",
    tags: ["formation", "learning", "cooperation", "teaching"],
    formation: {
      prerequisites: ["attention to others", "imitation", "teaching", "shared goals", "memory"],
      transition: "Communities preserved useful modifications across generations, creating a cumulative ratchet.",
      newlyPossible: ["complex tools", "shared conventions", "culture that outlives individuals"],
    },
    visual: { side: "left", depth: 1, emphasis: "secondary" },
  },
  {
    id: "human-organism-and-group",
    title: "Brain, body, and social group",
    aliases: ["embodied cognition", "human social system", "symbolic cognition"],
    kind: "entity",
    scale: "cognitive",
    stageId: "humans",
    primaryParentId: "humans",
    displayOrder: 2,
    summary: "Human cognition is organized across brains, dexterous bodies, development, and relationships rather than inside an isolated brain alone.",
    tags: ["structure", "brain", "body", "social cognition"],
    formation: {
      prerequisites: ["large associative brains", "hands and vocal control", "caregiving", "social dependence"],
      transition: "Development inside communicative groups coupled individual learning to collective practice.",
      newlyPossible: ["symbolic reasoning", "joint plans", "distributed problem solving"],
    },
    structure: { parts: ["brain", "body", "developmental history", "social partners"], systems: ["communication", "cooperation", "shared attention"] },
    visual: { side: "right", depth: 1, emphasis: "secondary" },
  },
  {
    id: "human-origins-science",
    title: "Human origins science",
    aliases: ["paleoanthropology", "archaeogenetics", "human evolution"],
    kind: "institution",
    scale: "technological",
    stageId: "humans",
    primaryParentId: "humans",
    displayOrder: 3,
    summary: "Fossils, artifacts, anatomy, environments, and genomes are combined to reconstruct a branching human history.",
    tags: ["discovery", "evidence", "anthropology"],
    formation: {
      prerequisites: ["geological dating", "archaeological excavation", "comparative anatomy", "genome sequencing"],
      transition: "Independent records were aligned in time and tested against population and evolutionary models.",
      newlyPossible: ["migration reconstructions", "lineage comparisons", "tests of behavioral change"],
    },
    discovery: [
      {
        id: "multi-record-synthesis",
        label: "Multi-record synthesis",
        dateLabel: "20th–21st centuries",
        summary: "Previously separate fossil, artifact, climate, and genetic records increasingly constrain one another.",
      },
    ],
    visual: { side: "left", depth: 2, emphasis: "context" },
  },
  {
    id: "culture",
    title: "Culture",
    aliases: ["symbolic culture", "shared meaning", "tradition"],
    kind: "stage",
    scale: "social",
    stageId: "culture",
    primaryParentId: "humans",
    displayOrder: 0,
    time: { label: "Cumulative symbolic culture across tens of thousands of years", startYearsAgo: 100_000, precision: "approximate" },
    summary: "Practices, symbols, norms, and stories became inherited socially, giving communities memory beyond any one person.",
    tags: ["language", "ritual", "tradition", "collective memory"],
    formation: {
      prerequisites: ["social learning", "symbolic communication", "shared attention", "intergenerational teaching"],
      transition: "Learned patterns were repeated, interpreted, revised, and transmitted across generations.",
      newlyPossible: ["durable traditions", "collective identities", "accumulated knowledge"],
    },
    structure: {
      parts: ["symbols", "practices", "norms", "stories", "artifacts"],
      systems: ["language", "ritual", "teaching", "collective memory"],
    },
    discovery: [
      {
        id: "comparative-anthropology",
        label: "Comparative anthropology",
        dateLabel: "19th–20th centuries",
        summary: "Fieldwork documented patterned variation without reducing culture to a single universal sequence.",
      },
      {
        id: "symbolic-archaeology",
        label: "Symbolic behavior in archaeology",
        dateLabel: "20th century onward",
        summary: "Art, ornament, burial, and patterned artifacts offered material traces of meaning-making.",
      },
    ],
    evidence: [
      {
        id: "material-patterns",
        label: "Patterned material culture",
        summary: "Repeated artifact styles and practices reveal learned group traditions.",
        sourceId: "atlas-lab:culture-material-patterns",
      },
      {
        id: "language-lineages",
        label: "Language relationships",
        summary: "Shared linguistic structures preserve traces of transmission, divergence, and contact.",
        sourceId: "atlas-lab:culture-language-lineages",
      },
    ],
    visual: { side: "center", depth: 0, emphasis: "primary" },
  },
  {
    id: "cultural-transmission",
    title: "Cultural transmission",
    aliases: ["tradition", "social inheritance", "intergenerational learning"],
    kind: "process",
    scale: "social",
    stageId: "culture",
    primaryParentId: "culture",
    displayOrder: 1,
    summary: "Communities preserve and transform learned information through imitation, teaching, performance, and record.",
    tags: ["formation", "learning", "memory"],
    formation: {
      prerequisites: ["social learners", "communication", "repeated practice", "trusted relationships"],
      transition: "Information survived individual turnover by being carried in people, routines, objects, and symbols.",
      newlyPossible: ["long traditions", "specialized knowledge", "rapid non-genetic adaptation"],
    },
    visual: { side: "left", depth: 1, emphasis: "secondary" },
  },
  {
    id: "language-and-symbols",
    title: "Language, symbols, and shared memory",
    aliases: ["language", "symbol systems", "oral tradition", "writing"],
    kind: "concept",
    scale: "social",
    stageId: "culture",
    primaryParentId: "culture",
    displayOrder: 2,
    summary: "Structured symbols let communities coordinate around absent, imagined, remembered, and possible things.",
    tags: ["structure", "language", "symbols", "memory", "writing"],
    formation: {
      prerequisites: ["shared attention", "vocal or gestural control", "conventions", "social learning"],
      transition: "Stable signs combined into expressive systems and were rehearsed across a community.",
      newlyPossible: ["narrative", "explicit instruction", "collective planning"],
    },
    structure: { parts: ["signs", "grammar", "shared concepts", "records and performances"], systems: ["conversation", "oral tradition", "symbolic classification"] },
    visual: { side: "right", depth: 1, emphasis: "secondary" },
  },
  {
    id: "material-culture",
    title: "Material traces of culture",
    aliases: ["archaeological artifacts", "symbolic artifacts", "cultural record"],
    kind: "event",
    scale: "civilizational",
    stageId: "culture",
    primaryParentId: "culture",
    displayOrder: 3,
    summary: "Objects, images, built spaces, and repeated production choices preserve evidence of learned meanings.",
    tags: ["evidence", "archaeology", "artifacts"],
    formation: {
      prerequisites: ["learned practices", "material production", "symbolic conventions", "preservation"],
      transition: "Repeated choices left durable patterns that could survive beyond their makers.",
      newlyPossible: ["comparative cultural histories", "tests of transmission", "reconstruction of past practices"],
    },
    evidence: [
      {
        id: "artifact-patterning",
        label: "Artifact patterning",
        summary: "Spatial and stylistic regularities distinguish shared traditions from isolated accidents.",
        sourceId: "atlas-lab:material-culture-patterning",
      },
    ],
    visual: { side: "left", depth: 2, emphasis: "context" },
  },
  {
    id: "civilization",
    title: "Civilization",
    aliases: ["complex societies", "cities and states", "urban civilization"],
    kind: "stage",
    scale: "civilizational",
    stageId: "civilization",
    primaryParentId: "culture",
    displayOrder: 0,
    time: { label: "Settled societies over roughly 12,000 years; early cities and states later", startYearsAgo: 12_000, endYearsAgo: 5_000, precision: "approximate" },
    summary: "Agricultural surplus, dense settlement, institutions, records, and infrastructure coordinated large populations.",
    tags: ["cities", "states", "agriculture", "law", "institutions"],
    formation: {
      prerequisites: ["cumulative culture", "food production and storage", "settlement", "coordination beyond kin groups"],
      transition: "Growing populations organized specialized labor, authority, exchange, public works, and durable records.",
      newlyPossible: ["cities and states", "formal law and administration", "large-scale infrastructure"],
    },
    structure: {
      parts: ["households", "settlements", "institutions", "infrastructure", "records"],
      systems: ["food and trade networks", "governance", "law", "specialized labor"],
    },
    discovery: [
      {
        id: "stratigraphic-archaeology",
        label: "Stratigraphic archaeology",
        dateLabel: "19th–20th centuries",
        summary: "Careful excavation placed artifacts, buildings, and ecological remains into chronological sequences.",
      },
      {
        id: "writing-decipherment",
        label: "Ancient writing deciphered",
        dateLabel: "19th century onward",
        summary: "Decoded scripts let administrative and personal records speak alongside material remains.",
      },
    ],
    evidence: [
      {
        id: "settlement-layers",
        label: "Settlement and infrastructure layers",
        summary: "Built environments reveal population scale, planning, production, and long-term change.",
        sourceId: "atlas-lab:civilization-settlement-layers",
      },
      {
        id: "administrative-records",
        label: "Administrative and legal records",
        summary: "Documents expose taxation, exchange, law, offices, and institutional memory.",
        sourceId: "atlas-lab:civilization-records",
      },
    ],
    visual: { side: "center", depth: 0, emphasis: "primary" },
  },
  {
    id: "institutional-coordination",
    title: "Institutional coordination",
    aliases: ["governance", "bureaucracy", "large-scale cooperation"],
    kind: "process",
    scale: "civilizational",
    stageId: "civilization",
    primaryParentId: "civilization",
    displayOrder: 1,
    summary: "Rules, roles, records, and enforcement coordinate people who do not all know one another personally.",
    tags: ["formation", "institutions", "administration"],
    formation: {
      prerequisites: ["surplus resources", "dense populations", "shared norms", "record keeping"],
      transition: "Responsibilities and decisions became attached to offices, procedures, and durable systems.",
      newlyPossible: ["public works", "large armies and markets", "intergenerational administration"],
    },
    visual: { side: "left", depth: 1, emphasis: "secondary" },
  },
  {
    id: "cities-states-and-infrastructure",
    title: "Cities, states, and infrastructure",
    aliases: ["urban systems", "state institutions", "roads and waterworks"],
    kind: "entity",
    scale: "civilizational",
    stageId: "civilization",
    primaryParentId: "civilization",
    displayOrder: 2,
    summary: "Settlements, governing institutions, transport, storage, and utilities form a coupled civilizational substrate.",
    tags: ["structure", "cities", "states", "infrastructure"],
    formation: {
      prerequisites: ["settled populations", "specialized labor", "resource flows", "collective construction"],
      transition: "Dense networks concentrated people and linked them through maintained physical and administrative systems.",
      newlyPossible: ["regional coordination", "specialist institutions", "large knowledge archives"],
    },
    structure: { parts: ["settlements", "governing offices", "roads and ports", "water and storage systems"], systems: ["administration", "trade", "public works"] },
    visual: { side: "right", depth: 1, emphasis: "secondary" },
  },
  {
    id: "written-and-archaeological-record",
    title: "Written and archaeological record",
    aliases: ["ancient records", "historical archaeology", "inscriptions"],
    kind: "event",
    scale: "civilizational",
    stageId: "civilization",
    primaryParentId: "civilization",
    displayOrder: 3,
    summary: "Texts, settlements, burials, tools, food remains, and landscapes provide overlapping records of complex societies.",
    tags: ["evidence", "history", "archaeology"],
    formation: {
      prerequisites: ["durable materials", "record keeping", "settlement layers", "preservation"],
      transition: "Institutional and everyday activity left multiple independent traces that could be aligned.",
      newlyPossible: ["institutional histories", "demographic estimates", "comparisons between records and lived conditions"],
    },
    evidence: [
      {
        id: "cross-record-agreement",
        label: "Cross-record agreement and tension",
        summary: "Texts and material evidence can corroborate one another or expose whose activity a record omitted.",
        sourceId: "atlas-lab:civilization-cross-record",
      },
    ],
    visual: { side: "left", depth: 2, emphasis: "context" },
  },
  {
    id: "science-technology-and-institutions",
    title: "Science, technology, and institutions",
    aliases: ["modern science", "technology", "research institutions", "industrial systems"],
    kind: "stage",
    scale: "technological",
    stageId: "science-technology-and-institutions",
    primaryParentId: "civilization",
    displayOrder: 0,
    time: { label: "Accelerating over roughly the last 500 years", startYearsAgo: 500, precision: "approximate" },
    summary: "Formal inquiry, instruments, publication, engineering, industry, and durable organizations amplified the reach of collective knowledge.",
    tags: ["science", "engineering", "institutions", "industry", "computing"],
    formation: {
      prerequisites: ["literacy and archives", "craft knowledge", "mathematics", "institutions", "long-distance exchange"],
      transition: "Repeatable measurement and criticism joined organized production, education, and technical iteration.",
      newlyPossible: ["high-precision prediction", "industrial-scale transformation", "global information networks"],
    },
    structure: {
      parts: ["methods", "instruments", "research communities", "technical systems", "institutions"],
      systems: ["publication and criticism", "education", "industry", "standards", "digital networks"],
    },
    discovery: [
      {
        id: "experimental-programs",
        label: "Organized experimental programs",
        dateLabel: "17th century onward",
        summary: "Shared methods, instruments, societies, and publication made findings more inspectable and cumulative.",
      },
      {
        id: "networked-computation",
        label: "Networked computation",
        dateLabel: "20th century",
        summary: "Programmable machines and communication networks transformed storage, modeling, and coordination.",
      },
    ],
    evidence: [
      {
        id: "reproducible-measurement",
        label: "Reproducible measurement records",
        summary: "Methods and uncertainty can be compared across instruments, teams, and time.",
        sourceId: "atlas-lab:science-reproducible-measurement",
      },
      {
        id: "technical-lineage",
        label: "Traceable technical lineages",
        summary: "Designs, standards, prototypes, and performance records document cumulative engineering change.",
        sourceId: "atlas-lab:technology-lineages",
      },
    ],
    visual: { side: "center", depth: 0, emphasis: "primary" },
  },
  {
    id: "scientific-method",
    title: "Scientific inquiry",
    aliases: ["scientific method", "experiment", "hypothesis testing"],
    kind: "process",
    scale: "technological",
    stageId: "science-technology-and-institutions",
    primaryParentId: "science-technology-and-institutions",
    displayOrder: 1,
    summary: "Observation, modeling, intervention, criticism, and replication create an error-correcting knowledge process.",
    tags: ["formation", "science", "experiment", "replication"],
    formation: {
      prerequisites: ["measurement", "formal models", "record keeping", "critical communities"],
      transition: "Claims were exposed to shared tests, documented methods, revision, and comparison with alternatives.",
      newlyPossible: ["cumulative reliable models", "precision engineering", "organized uncertainty reduction"],
    },
    visual: { side: "left", depth: 1, emphasis: "secondary" },
  },
  {
    id: "institutions-instruments-and-networks",
    title: "Institutions, instruments, and networks",
    aliases: ["laboratories", "universities", "internet", "technical infrastructure"],
    kind: "institution",
    scale: "technological",
    stageId: "science-technology-and-institutions",
    primaryParentId: "science-technology-and-institutions",
    displayOrder: 2,
    summary: "Knowledge and technical power depend on coordinated people, material tools, standards, archives, and communication systems.",
    tags: ["structure", "institutions", "instruments", "networks"],
    formation: {
      prerequisites: ["specialized education", "funding and governance", "manufacturing", "communication standards"],
      transition: "Organizations maintained equipment, roles, archives, and shared protocols beyond individual careers.",
      newlyPossible: ["large collaborations", "global computation", "persistent research programs"],
    },
    structure: { parts: ["people and roles", "laboratories", "archives", "standards", "communication networks"], systems: ["research", "engineering", "education", "industry"] },
    visual: { side: "right", depth: 1, emphasis: "secondary" },
  },
  {
    id: "reproducible-experiments",
    title: "Reproducible experiments",
    aliases: ["replication", "controlled experiment", "measurement record"],
    kind: "event",
    scale: "technological",
    stageId: "science-technology-and-institutions",
    primaryParentId: "science-technology-and-institutions",
    displayOrder: 3,
    summary: "Documented interventions and measurements let findings be challenged, refined, or reproduced by others.",
    tags: ["evidence", "discovery", "method"],
    formation: {
      prerequisites: ["calibrated instruments", "shared protocols", "recorded uncertainty", "critical review"],
      transition: "Procedures made observations inspectable beyond the original investigator and setting.",
      newlyPossible: ["replication", "meta-analysis", "technical standards"],
    },
    evidence: [
      {
        id: "method-result-linkage",
        label: "Method-to-result linkage",
        summary: "Recorded materials, procedures, observations, and uncertainty preserve how a result was obtained.",
        sourceId: "atlas-lab:reproducible-method-result",
      },
    ],
    visual: { side: "left", depth: 2, emphasis: "context" },
  },
  {
    id: "present-day",
    title: "The present planetary moment",
    aliases: ["present day", "today", "now", "contemporary world"],
    kind: "stage",
    scale: "civilizational",
    stageId: "present-day",
    primaryParentId: "science-technology-and-institutions",
    displayOrder: 0,
    time: { label: "Now", startYearsAgo: 0, endYearsAgo: 0, precision: "exact" },
    summary: "Billions of people, ecosystems, institutions, industries, and digital systems are coupled in real time at planetary scale.",
    tags: ["global systems", "Anthropocene", "internet", "climate", "future"],
    formation: {
      prerequisites: ["industrial capacity", "global institutions", "energy and transport networks", "digital communication", "a living planet"],
      transition: "Previously regional systems became tightly connected through flows of matter, energy, money, people, and information.",
      newlyPossible: ["near-instant global coordination", "planetary measurement", "planetary-scale risk and stewardship"],
    },
    structure: {
      parts: ["people and communities", "biosphere", "cities and infrastructure", "institutions", "digital networks"],
      systems: ["climate and Earth systems", "global trade", "public health", "information networks", "governance"],
    },
    discovery: [
      {
        id: "whole-earth-observation",
        label: "Whole-Earth observation",
        dateLabel: "20th century onward",
        summary: "Satellites and global sensor networks made planetary processes measurable as connected systems.",
      },
      {
        id: "networked-world",
        label: "A networked world",
        dateLabel: "Late 20th–21st centuries",
        summary: "Digital communication made global information flow a daily social infrastructure.",
      },
    ],
    evidence: [
      {
        id: "earth-observation-series",
        label: "Global Earth-observation series",
        summary: "Satellites, stations, and ocean sensors jointly track planetary change through time.",
        sourceId: "atlas-lab:present-earth-observation",
      },
      {
        id: "coupled-network-records",
        label: "Coupled network records",
        summary: "Trade, mobility, communications, energy, and ecological data reveal linked global systems.",
        sourceId: "atlas-lab:present-network-records",
      },
    ],
    visual: { side: "center", depth: 0, emphasis: "primary" },
  },
  {
    id: "planetary-coordination",
    title: "Planetary coordination",
    aliases: ["global cooperation", "planetary stewardship", "collective action"],
    kind: "process",
    scale: "civilizational",
    stageId: "present-day",
    primaryParentId: "present-day",
    displayOrder: 1,
    summary: "Institutions and publics attempt to perceive and act on problems whose causes and effects cross borders.",
    tags: ["formation", "coordination", "stewardship", "governance"],
    formation: {
      prerequisites: ["global communication", "shared measurement", "institutions", "public legitimacy"],
      transition: "Local observations and interests were aggregated into planetary models, negotiations, and joint programs.",
      newlyPossible: ["coordinated risk response", "shared standards", "deliberate stewardship"],
    },
    visual: { side: "left", depth: 1, emphasis: "secondary" },
  },
  {
    id: "global-networks",
    title: "Ecological, industrial, and information networks",
    aliases: ["global networks", "internet", "supply chains", "Earth system"],
    kind: "entity",
    scale: "civilizational",
    stageId: "present-day",
    primaryParentId: "present-day",
    displayOrder: 2,
    summary: "Present life is organized through overlapping networks that move energy, matter, organisms, goods, and information.",
    tags: ["structure", "networks", "biosphere", "infrastructure"],
    formation: {
      prerequisites: ["biospheric cycles", "infrastructure", "markets and institutions", "digital communication"],
      transition: "Dense connectivity made distant systems mutually dependent and capable of rapid cascade.",
      newlyPossible: ["global collaboration", "real-time services", "systemic shocks"],
    },
    structure: { parts: ["ecosystems", "cities", "supply chains", "energy grids", "digital platforms"], systems: ["biosphere", "world economy", "internet", "governance"] },
    visual: { side: "right", depth: 1, emphasis: "secondary" },
  },
  {
    id: "earth-observation-systems",
    title: "Earth-observation systems",
    aliases: ["satellite monitoring", "global sensors", "planetary dashboard"],
    kind: "technology",
    scale: "technological",
    stageId: "present-day",
    primaryParentId: "present-day",
    displayOrder: 3,
    summary: "Satellites, field stations, ocean platforms, and models create a shared evidence layer for planetary change.",
    tags: ["evidence", "satellite", "climate", "monitoring"],
    formation: {
      prerequisites: ["remote sensing", "global standards", "long-lived instruments", "computational models"],
      transition: "Measurements from many platforms were calibrated, combined, and tracked through time.",
      newlyPossible: ["planetary trend detection", "early warning", "publicly inspectable global baselines"],
    },
    evidence: [
      {
        id: "cross-platform-series",
        label: "Cross-platform time series",
        summary: "Independent instruments and methods can overlap, cross-check, and extend planetary records.",
        sourceId: "atlas-lab:earth-observation-cross-platform",
      },
    ],
    visual: { side: "left", depth: 2, emphasis: "context" },
  },
];

const stageSpineEdges: AtlasEdge[] = [
  { id: "spine-01-02", sourceId: "early-universe", targetId: "fundamental-forces-and-particles", type: "primary_emergence", label: "Cooling reveals durable particle regimes", primary: true, lenses: ["formation"] },
  { id: "spine-02-03", sourceId: "fundamental-forces-and-particles", targetId: "atoms", type: "primary_emergence", label: "Particles bind into neutral atoms", primary: true, lenses: ["formation"] },
  { id: "spine-03-04", sourceId: "atoms", targetId: "stars-and-heavy-elements", type: "primary_emergence", label: "Gas collapses into stellar furnaces", primary: true, lenses: ["formation"] },
  { id: "spine-04-05", sourceId: "stars-and-heavy-elements", targetId: "planetary-systems", type: "primary_emergence", label: "Enriched stellar disks form worlds", primary: true, lenses: ["formation"] },
  { id: "spine-05-06", sourceId: "planetary-systems", targetId: "earth", type: "primary_emergence", label: "A rocky world differentiates and cycles", primary: true, lenses: ["formation"] },
  { id: "spine-06-07", sourceId: "earth", targetId: "life", type: "primary_emergence", label: "Geochemistry organizes into living systems", primary: true, lenses: ["formation"] },
  { id: "spine-07-08", sourceId: "life", targetId: "multicellular-life", type: "primary_emergence", label: "Cells cooperate and specialize", primary: true, lenses: ["formation"] },
  { id: "spine-08-09", sourceId: "multicellular-life", targetId: "nervous-systems", type: "primary_emergence", label: "Bodies develop fast integrated signaling", primary: true, lenses: ["formation"] },
  { id: "spine-09-10", sourceId: "nervous-systems", targetId: "humans", type: "primary_emergence", label: "A social primate lineage expands cumulative cognition", primary: true, lenses: ["formation"] },
  { id: "spine-10-11", sourceId: "humans", targetId: "culture", type: "primary_emergence", label: "Learning becomes durable social inheritance", primary: true, lenses: ["formation"] },
  { id: "spine-11-12", sourceId: "culture", targetId: "civilization", type: "primary_emergence", label: "Institutions coordinate dense settled populations", primary: true, lenses: ["formation"] },
  { id: "spine-12-13", sourceId: "civilization", targetId: "science-technology-and-institutions", type: "primary_emergence", label: "Organized inquiry and engineering become cumulative systems", primary: true, lenses: ["formation"] },
  { id: "spine-13-14", sourceId: "science-technology-and-institutions", targetId: "present-day", type: "primary_emergence", label: "Technical and institutional networks couple the planet", primary: true, lenses: ["formation"] },
];

const branchPrimaryEdges: AtlasEdge[] = [
  { id: "primary-expansion-and-cooling", sourceId: "early-universe", targetId: "expansion-and-cooling", type: "enabled", label: "The hot expanding state undergoes cooling", primary: true, lenses: ["formation"] },
  { id: "primary-primordial-plasma", sourceId: "early-universe", targetId: "primordial-plasma", type: "composed_of", label: "Early matter and radiation form a coupled plasma", primary: true, lenses: ["structure"] },
  { id: "primary-cosmic-microwave-background", sourceId: "early-universe", targetId: "cosmic-microwave-background", type: "evidenced_by", label: "Relic radiation preserves the early thermal record", primary: true, lenses: ["evidence"] },
  { id: "primary-particle-stabilization", sourceId: "fundamental-forces-and-particles", targetId: "particle-stabilization", type: "enabled", label: "Interactions govern which populations persist", primary: true, lenses: ["formation"] },
  { id: "primary-quarks-and-leptons", sourceId: "fundamental-forces-and-particles", targetId: "quarks-and-leptons", type: "composed_of", label: "Matter is organized from elementary particle families", primary: true, lenses: ["structure"] },
  { id: "primary-particle-collision-traces", sourceId: "fundamental-forces-and-particles", targetId: "particle-collision-traces", type: "evidenced_by", label: "Collisions expose interaction patterns", primary: true, lenses: ["evidence"] },
  { id: "primary-recombination", sourceId: "atoms", targetId: "recombination", type: "emerged_from", label: "Neutral atoms emerged through recombination", primary: true, lenses: ["formation"] },
  { id: "primary-atomic-structure", sourceId: "atoms", targetId: "atomic-structure", type: "composed_of", label: "Atoms contain nuclei and bound electrons", primary: true, lenses: ["structure"] },
  { id: "primary-atomic-theory-milestones", sourceId: "atoms", targetId: "atomic-theory-milestones", type: "discovered_by", label: "Atomic structure was reconstructed through successive models", primary: true, lenses: ["discovery"] },
  { id: "primary-stellar-fusion", sourceId: "stars-and-heavy-elements", targetId: "stellar-fusion", type: "emerged_from", label: "Long-lived stars arise with fusion ignition", primary: true, lenses: ["formation"] },
  { id: "primary-heavy-elements", sourceId: "stars-and-heavy-elements", targetId: "heavy-elements", type: "composed_of", label: "Stellar history supplies heavier nuclei", primary: true, lenses: ["structure"] },
  { id: "primary-stellar-spectroscopy", sourceId: "stars-and-heavy-elements", targetId: "stellar-spectroscopy", type: "evidenced_by", label: "Starlight records composition and motion", primary: true, lenses: ["evidence"] },
  { id: "primary-planetary-accretion", sourceId: "planetary-systems", targetId: "planetary-accretion", type: "emerged_from", label: "Planetary systems emerge through disk accretion", primary: true, lenses: ["formation"] },
  { id: "primary-planetary-architecture", sourceId: "planetary-systems", targetId: "planetary-architecture", type: "composed_of", label: "Stars, worlds, moons, and small bodies form a system", primary: true, lenses: ["structure"] },
  { id: "primary-exoplanet-discovery", sourceId: "planetary-systems", targetId: "exoplanet-discovery", type: "discovered_by", label: "Other planetary systems became visible through precision surveys", primary: true, lenses: ["discovery"] },
  { id: "primary-plate-tectonics", sourceId: "earth", targetId: "plate-tectonics", type: "enabled", label: "Internal heat enables long-running tectonic activity", primary: true, lenses: ["formation"] },
  { id: "primary-earth-systems", sourceId: "earth", targetId: "earth-systems", type: "composed_of", label: "Earth contains interacting layers and reservoirs", primary: true, lenses: ["structure"] },
  { id: "primary-deep-time-geoscience", sourceId: "earth", targetId: "deep-time-geoscience", type: "discovered_by", label: "Earth history was reconstructed through deep-time geoscience", primary: true, lenses: ["discovery"] },
  { id: "primary-evolution-by-selection", sourceId: "life", targetId: "evolution-by-selection", type: "enabled", label: "Heritable living systems enable evolution by selection", primary: true, lenses: ["formation"] },
  { id: "primary-cells", sourceId: "life", targetId: "cells", type: "composed_of", label: "Cellular organization integrates life's core functions", primary: true, lenses: ["structure"] },
  { id: "primary-microscopy-and-evolutionary-theory", sourceId: "life", targetId: "microscopy-and-evolutionary-theory", type: "discovered_by", label: "Life's organization and history were clarified through microscopy and theory", primary: true, lenses: ["discovery"] },
  { id: "primary-cell-specialization", sourceId: "multicellular-life", targetId: "cell-specialization", type: "emerged_from", label: "Complex bodies emerge through coordinated specialization", primary: true, lenses: ["formation"] },
  { id: "primary-tissues-and-organs", sourceId: "multicellular-life", targetId: "tissues-and-organs", type: "composed_of", label: "Multicellular bodies contain tissues and organs", primary: true, lenses: ["structure"] },
  { id: "primary-multicellular-fossil-record", sourceId: "multicellular-life", targetId: "multicellular-fossil-record", type: "evidenced_by", label: "Fossils preserve body and behavior traces", primary: true, lenses: ["evidence"] },
  { id: "primary-neural-signaling", sourceId: "nervous-systems", targetId: "neural-signaling", type: "enabled", label: "Nervous systems enable rapid integrated signaling", primary: true, lenses: ["formation"] },
  { id: "primary-neurons-and-networks", sourceId: "nervous-systems", targetId: "neurons-and-networks", type: "composed_of", label: "Nervous systems contain communicating neural networks", primary: true, lenses: ["structure"] },
  { id: "primary-neuron-doctrine", sourceId: "nervous-systems", targetId: "neuron-doctrine", type: "discovered_by", label: "Neural organization was reframed by the neuron doctrine", primary: true, lenses: ["discovery"] },
  { id: "primary-cumulative-social-learning", sourceId: "humans", targetId: "cumulative-social-learning", type: "enabled", label: "Human social cognition enables cumulative learning", primary: true, lenses: ["formation"] },
  { id: "primary-human-organism-and-group", sourceId: "humans", targetId: "human-organism-and-group", type: "composed_of", label: "Human capacity spans brain, body, development, and group", primary: true, lenses: ["structure"] },
  { id: "primary-human-origins-science", sourceId: "humans", targetId: "human-origins-science", type: "discovered_by", label: "Human history is reconstructed through multiple sciences", primary: true, lenses: ["discovery"] },
  { id: "primary-cultural-transmission", sourceId: "culture", targetId: "cultural-transmission", type: "emerged_from", label: "Culture persists through social transmission", primary: true, lenses: ["formation"] },
  { id: "primary-language-and-symbols", sourceId: "culture", targetId: "language-and-symbols", type: "composed_of", label: "Culture is carried by symbols, language, and memory", primary: true, lenses: ["structure"] },
  { id: "primary-material-culture", sourceId: "culture", targetId: "material-culture", type: "evidenced_by", label: "Artifacts preserve learned patterns", primary: true, lenses: ["evidence"] },
  { id: "primary-institutional-coordination", sourceId: "civilization", targetId: "institutional-coordination", type: "emerged_from", label: "Large societies emerge through durable coordination", primary: true, lenses: ["formation"] },
  { id: "primary-cities-states-and-infrastructure", sourceId: "civilization", targetId: "cities-states-and-infrastructure", type: "composed_of", label: "Civilizations contain settlements, institutions, and infrastructure", primary: true, lenses: ["structure"] },
  { id: "primary-written-and-archaeological-record", sourceId: "civilization", targetId: "written-and-archaeological-record", type: "evidenced_by", label: "Records and remains preserve civilizational history", primary: true, lenses: ["evidence"] },
  { id: "primary-scientific-method", sourceId: "science-technology-and-institutions", targetId: "scientific-method", type: "emerged_from", label: "Reliable models emerge through organized inquiry", primary: true, lenses: ["formation"] },
  { id: "primary-institutions-instruments-and-networks", sourceId: "science-technology-and-institutions", targetId: "institutions-instruments-and-networks", type: "composed_of", label: "Knowledge systems contain people, tools, standards, and networks", primary: true, lenses: ["structure"] },
  { id: "primary-reproducible-experiments", sourceId: "science-technology-and-institutions", targetId: "reproducible-experiments", type: "evidenced_by", label: "Documented experiments expose how claims were tested", primary: true, lenses: ["evidence"] },
  { id: "primary-planetary-coordination", sourceId: "present-day", targetId: "planetary-coordination", type: "enabled", label: "Global connection enables planetary coordination", primary: true, lenses: ["formation"] },
  { id: "primary-global-networks", sourceId: "present-day", targetId: "global-networks", type: "composed_of", label: "The present contains overlapping ecological and technical networks", primary: true, lenses: ["structure"] },
  { id: "primary-earth-observation-systems", sourceId: "present-day", targetId: "earth-observation-systems", type: "evidenced_by", label: "Observation systems expose planetary-scale change", primary: true, lenses: ["evidence"] },
];

const secondaryEdges: AtlasEdge[] = [
  { id: "cross-plasma-recombination", sourceId: "recombination", targetId: "primordial-plasma", type: "emerged_from", label: "Neutral matter formed from the cooling plasma", lenses: ["formation"] },
  { id: "cross-atoms-require-particles", sourceId: "atoms", targetId: "quarks-and-leptons", type: "requires", label: "Atoms require stable nuclei and electrons", lenses: ["formation", "structure"] },
  { id: "cross-heavy-elements-enable-planets", sourceId: "heavy-elements", targetId: "planetary-systems", type: "enabled", label: "Enrichment supplies rocky and chemically diverse material", lenses: ["formation"] },
  { id: "cross-atomic-spectra-stellar", sourceId: "stellar-spectroscopy", targetId: "atomic-structure", type: "requires", label: "Stellar spectra are interpreted through atomic transitions", lenses: ["structure", "discovery", "evidence"] },
  { id: "cross-earth-requires-heavy-elements", sourceId: "earth", targetId: "heavy-elements", type: "requires", label: "A rocky differentiated Earth requires enriched material", lenses: ["formation", "structure"] },
  { id: "cross-life-requires-chemistry", sourceId: "life", targetId: "atomic-structure", type: "requires", label: "Living chemistry depends on atomic structure and bonding", lenses: ["formation", "structure"] },
  { id: "cross-tectonics-influences-life", sourceId: "plate-tectonics", targetId: "life", type: "influenced", label: "Long geochemical cycling reshapes environments for life", lenses: ["formation"] },
  { id: "cross-cells-enable-multicellular", sourceId: "cells", targetId: "multicellular-life", type: "enabled", label: "Cells are the cooperating units of multicellular bodies", lenses: ["formation", "structure"] },
  { id: "cross-tissues-enable-nerves", sourceId: "tissues-and-organs", targetId: "nervous-systems", type: "enabled", label: "Differentiated bodies create roles for integrated control", lenses: ["formation", "structure"] },
  { id: "cross-neural-human", sourceId: "humans", targetId: "neurons-and-networks", type: "requires", label: "Human cognition depends on embodied neural networks", lenses: ["formation", "structure"] },
  { id: "cross-learning-culture", sourceId: "cumulative-social-learning", targetId: "culture", type: "enabled", label: "Cumulative learning lets culture outlive individuals", lenses: ["formation"] },
  { id: "cross-language-civilization", sourceId: "language-and-symbols", targetId: "civilization", type: "enabled", label: "Symbolic records support coordination across time and distance", lenses: ["formation"] },
  { id: "cross-civilization-science", sourceId: "science-technology-and-institutions", targetId: "cities-states-and-infrastructure", type: "requires", label: "Organized knowledge depends on durable civilizational infrastructure", lenses: ["formation", "structure"] },
  { id: "cross-networks-present", sourceId: "institutions-instruments-and-networks", targetId: "present-day", type: "enabled", label: "Technical networks couple activity at planetary scale", lenses: ["formation"] },
  { id: "cross-evidence-method", sourceId: "earth-observation-systems", targetId: "scientific-method", type: "requires", label: "Planetary monitoring depends on calibrated, critical inquiry", lenses: ["evidence", "structure"] },
  { id: "cross-cmb-spectroscopy", sourceId: "cosmic-microwave-background", targetId: "stellar-spectroscopy", type: "cross_link", label: "Both infer inaccessible histories from structured light", lenses: ["discovery", "evidence"] },
];

export const atlasLabSnapshot: AtlasSnapshot = {
  schemaVersion: 1,
  id: "atlas-lab-developmental-history-v1",
  title: "Atlas V2 — How reality became organized",
  rootNodeId: "early-universe",
  stages,
  nodes,
  edges: [...stageSpineEdges, ...branchPrimaryEdges, ...secondaryEdges],
};

export const atlasLabStageById = Object.freeze(
  Object.fromEntries(atlasLabSnapshot.stages.map(stage => [stage.id, stage])),
) as Readonly<Record<string, AtlasStage>>;

export const atlasLabNodeById = Object.freeze(
  Object.fromEntries(atlasLabSnapshot.nodes.map(node => [node.id, node])),
) as Readonly<Record<string, AtlasNode>>;

export const atlasLabNodesByStageId = Object.freeze(
  Object.fromEntries(atlasLabSnapshot.stages.map(stage => [
    stage.id,
    atlasLabSnapshot.nodes
      .filter(node => node.stageId === stage.id)
      .sort((a, b) => a.displayOrder - b.displayOrder),
  ])),
) as Readonly<Record<string, AtlasNode[]>>;

export function getAtlasLabStage(stageId: string) {
  return atlasLabStageById[stageId];
}

export function getAtlasLabNode(nodeId: string) {
  return atlasLabNodeById[nodeId];
}

export function getAtlasLabStageNodes(stageId: string) {
  return atlasLabNodesByStageId[stageId] || [];
}

export function normalizeAtlasLabState(
  stageParam?: string,
  nodeParam?: string,
  lensParam?: string,
): AtlasLabUrlState {
  const node = nodeParam ? atlasLabNodeById[nodeParam] : undefined;
  const stageId = node?.stageId
    || (stageParam && atlasLabStageById[stageParam] ? stageParam : atlasLabSnapshot.stages[0].id);
  const lens = ATLAS_LENSES.includes(lensParam as AtlasLens) ? lensParam as AtlasLens : "formation";

  return {
    stageId,
    ...(node ? { nodeId: node.id } : {}),
    lens,
  };
}
